-d E:\LearningMeterials\HardwareCourseDesign\temp_humi_display\impl\gwsynthesis\SPIlcd_prj.vg
-p GW1N-1-QFN48-6
-pn GW1N-LV1QN48C6/I5
-cst E:\LearningMeterials\HardwareCourseDesign\temp_humi_display\src\LCDQig_pre1.cst
-cfg E:\LearningMeterials\HardwareCourseDesign\temp_humi_display\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
