-d F:\hardware_design\gowin_fpga_clock\impl\gwsynthesis\SPIlcd_prj.vg
-p GW1N-1-QFN48-6
-pn GW1N-LV1QN48C6/I5
-cst F:\hardware_design\gowin_fpga_clock\src\LCDQig_pre1.cst
-cfg F:\hardware_design\gowin_fpga_clock\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
